<a href="https://colab.research.google.com/github/rishavk77-bit/Localrepo/blob/main/dl1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
print("Hello")

In [ ]:
#Number
t1 = torch.tensor(4.)
t1

In [ ]:
t1.dtype

In [ ]:
#Vectors or 1d tensor
t2 = torch.tensor([1.,2,3,4])
t2

In [ ]:
t2.dtype

In [ ]:
# Matrix
t3 = torch.tensor([[5., 6],
                   [7, 8],
                   [9, 10]])
t3

In [ ]:
# 3-dimensional array
t4 = torch.tensor([
    [[11, 12, 13],
     [13, 14, 15]],
    [[15, 16, 17],
     [17, 18, 19.]]])
t4

In [ ]:
lis = [t1,t2,t3,t4]
for t in lis:
  print(t,"\n",t.shape,"\n","\n")

In [ ]:
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)
x, w, b


In [ ]:
# Arithmetic operations
y = w * x + b
y

In [ ]:
# Compute derivatives
y.backward()

In [78]:
print("dy/dx",x.grad)
print("dy/dw",w.grad)
print("dy/db",b.grad)


AttributeError: 'numpy.ndarray' object has no attribute 'grad'

In [79]:
## Create a tensor that has a fixed values for every elements
t6 = torch.full((3,2),42)
print(t6)

tensor([[42, 42],
        [42, 42],
        [42, 42]])


In [80]:
t7 = torch.cat((t3,t6))
print(t7)
print(t7.shape)

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [42., 42.],
        [42., 42.],
        [42., 42.]])
torch.Size([6, 2])


In [81]:
t8 = torch.sin(t7)
print(t8)
t8.shape

tensor([[-0.9589, -0.2794],
        [ 0.6570,  0.9894],
        [ 0.4121, -0.5440],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165]])


torch.Size([6, 2])

In [82]:
t9 = t8.reshape(3,2,2)
print(t9)
t9.shape

tensor([[[-0.9589, -0.2794],
         [ 0.6570,  0.9894]],

        [[ 0.4121, -0.5440],
         [-0.9165, -0.9165]],

        [[-0.9165, -0.9165],
         [-0.9165, -0.9165]]])


torch.Size([3, 2, 2])

In [83]:
import numpy as np

x = np.array([[1, 2], [3, 4.]])
x

array([[1., 2.],
       [3., 4.]])

In [84]:
# Convert the numpy array to a torch tensor.
y = torch.from_numpy(x)
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [85]:
x.dtype, y.dtype

(dtype('float64'), torch.float64)

In [86]:
# Convert a torch tensor to a numpy array
z = y.numpy()
z

array([[1., 2.],
       [3., 4.]])

In [87]:
!pip install numpy torch torchvision torchaudio

In [133]:
import numpy as np
import torch

# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70]], dtype='float32')


In [134]:
# Targets (apples, oranges)
targets = np.array([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119]], dtype='float32')

In [135]:
# Convert inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [136]:
#Weights and biases
w = torch.randn(2,3,requires_grad=True)
b = torch.randn(2,requires_grad=True)
print(w)
print(b)

tensor([[ 1.0460, -0.0205,  0.4487],
        [-1.7413,  0.1942,  0.7665]], requires_grad=True)
tensor([0.7153, 0.7066], requires_grad=True)


In [137]:
def model(x):
  return x @ w.t() + b

In [138]:
#generate the prediction
preds = model(inputs)
print(preds)


tensor([[  94.9919,  -80.4378],
        [ 122.8113,  -91.6066],
        [ 114.9936,  -80.3086],
        [ 123.1246, -140.1946],
        [ 102.3280,  -47.1456]], grad_fn=<AddBackward0>)


In [139]:
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [140]:
diff = preds - targets
print(torch.sum(diff**2)/diff.numel())

tensor(17774.2910, grad_fn=<DivBackward0>)


In [141]:
# MSE loss
def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()

In [142]:
# Compute loss
loss = mse(preds, targets)
print(loss)

tensor(17774.2910, grad_fn=<DivBackward0>)


In [143]:
loss.backward(retain_graph=True)  # First backward call
loss.backward(retain_graph=True)  # Second backward call (if needed)


In [144]:
print(w)
print(w.grad)

tensor([[ 1.0460, -0.0205,  0.4487],
        [-1.7413,  0.1942,  0.7665]], requires_grad=True)
tensor([[  6628.4111,   4015.5376,   3125.9104],
        [-30641.9609, -31672.5625, -19741.5742]])


In [145]:
print(b)
print(b.grad)

tensor([0.7153, 0.7066], requires_grad=True)
tensor([  70.8998, -359.8773])


In [146]:
print(w)
w.grad

tensor([[ 1.0460, -0.0205,  0.4487],
        [-1.7413,  0.1942,  0.7665]], requires_grad=True)


tensor([[  6628.4111,   4015.5376,   3125.9104],
        [-30641.9609, -31672.5625, -19741.5742]])

In [147]:
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5

In [148]:
w,b

(tensor([[ 0.9797, -0.0606,  0.4174],
         [-1.4349,  0.5109,  0.9639]], requires_grad=True),
 tensor([0.7146, 0.7102], requires_grad=True))

In [149]:
preds = model(inputs)
loss = mse(preds,targets)
print(loss)

tensor(7911.5850, grad_fn=<DivBackward0>)


In [150]:
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


In [151]:
# Generate predictions
preds = model(inputs)
print(preds)

tensor([[ 86.1179, -28.3561],
        [111.2445, -23.2123],
        [102.0323,   0.2449],
        [113.4797, -88.0126],
        [ 91.7106,  18.2257]], grad_fn=<AddBackward0>)


In [152]:
# Calculate the loss
loss = mse(preds, targets)
print(loss)

tensor(7911.5850, grad_fn=<DivBackward0>)


In [153]:
# Compute gradients
loss.backward()
print(w.grad)
print(b.grad)

tensor([[  2405.3259,   1051.1189,    968.2168],
        [ -9947.5439, -10071.9199,  -6311.6729]])
tensor([  24.7170, -116.2221])


In [154]:
# Adjust weights & reset gradients
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [155]:
print(w)
print(b)


tensor([[ 0.9556, -0.0711,  0.4077],
        [-1.3354,  0.6116,  1.0271]], requires_grad=True)
tensor([0.7143, 0.7114], requires_grad=True)


In [156]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(5651.8584, grad_fn=<DivBackward0>)


In [160]:
w.grad.zero_()
b.grad.zero_()

tensor([0., 0.])

In [161]:
for i in range(100):
  loss = mse(preds,targets)
  loss.backward(retain_graph=True)  # First backward call
  loss.backward(retain_graph=True)  # Second backward call (if needed)

  with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()


In [162]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(6.8245e+09, grad_fn=<DivBackward0>)
